import type { AdsAdminState } from './store';

export const DEMO_STATE: AdsAdminState = {
  schemaVersion: 1,
  campaigns: [
    {
      id: 'cmp-summer-game',
      name: '暑期游戏新用户推广',
      objective: '应用推广',
      status: '投放中',
      dailyBudget: 320,
      totalBudget: 9600,
      spend: 4368.42,
      impressions: 684230,
      clicks: 12842,
      conversions: 786,
      bid: 0.68,
      startDate: '2026-08-01',
      endDate: '2026-09-15',
      region: '中国大陆',
      devices: ['Android', 'iOS'],
      updatedAt: '2026-08-28T09:20:00.000Z',
    },
    {
      id: 'cmp-harmonica',
      name: '蓝调口琴课程引流',
      objective: '网站访问',
      status: '预算受限',
      dailyBudget: 80,
      totalBudget: 2400,
      spend: 1826.8,
      impressions: 248920,
      clicks: 5486,
      conversions: 314,
      bid: 0.42,
      startDate: '2026-08-10',
      endDate: '2026-09-10',
      region: '中国大陆',
      devices: ['桌面端', '移动端'],
      updatedAt: '2026-08-28T08:10:00.000Z',
    },
    {
      id: 'cmp-creator-leads',
      name: '独立开发者合作招募',
      objective: '获取线索',
      status: '审核中',
      dailyBudget: 150,
      totalBudget: 4500,
      spend: 0,
      impressions: 0,
      clicks: 0,
      conversions: 0,
      bid: 0.9,
      startDate: '2026-09-01',
      endDate: '2026-09-30',
      region: '全国重点城市',
      devices: ['桌面端', '移动端'],
      updatedAt: '2026-08-27T15:40:00.000Z',
    },
    {
      id: 'cmp-autumn-draft',
      name: '秋季品牌活动草稿',
      objective: '网站访问',
      status: '草稿',
      dailyBudget: 120,
      totalBudget: 3600,
      spend: 0,
      impressions: 0,
      clicks: 0,
      conversions: 0,
      bid: 0.55,
      startDate: '2026-09-05',
      endDate: '2026-10-05',
      region: '中国大陆',
      devices: ['移动端'],
      updatedAt: '2026-08-26T11:12:00.000Z',
    },
    {
      id: 'cmp-launch-ended',
      name: '七月版本发布推广',
      objective: '应用推广',
      status: '已结束',
      dailyBudget: 260,
      totalBudget: 5200,
      spend: 5086.35,
      impressions: 792180,
      clicks: 15344,
      conversions: 1026,
      bid: 0.6,
      startDate: '2026-07-01',
      endDate: '2026-07-20',
      region: '中国大陆',
      devices: ['Android', 'iOS'],
      updatedAt: '2026-07-20T23:59:00.000Z',
    },
  ],
  ads: [
    {
      id: 'ad-neon-hero',
      campaignId: 'cmp-summer-game',
      name: '霓虹英雄主视觉',
      headline: '踏入神话战场，开启全新冒险',
      description: '免费体验手绘动作游戏，完成首章即可领取限定外观。',
      callToAction: '立即试玩',
      format: '原生卡片',
      reviewStatus: '审核通过',
      theme: 'violet',
    },
    {
      id: 'ad-harp-course',
      campaignId: 'cmp-harmonica',
      name: '口琴课程横幅',
      headline: '跟随下落音符练习蓝调口琴',
      description: 'C调十孔口琴在线练习，包含节奏试听和分段学习。',
      callToAction: '免费练习',
      format: '横幅',
      reviewStatus: '审核通过',
      theme: 'amber',
    },
    {
      id: 'ad-creator-leads',
      campaignId: 'cmp-creator-leads',
      name: '开发者招募卡片',
      headline: '让你的独立作品被更多人看见',
      description: '加入创作者合作计划，获得站内流量与联合推广机会。',
      callToAction: '提交作品',
      format: '原生卡片',
      reviewStatus: '审核中',
      theme: 'cyan',
    },
  ],
  conversionActions: [
    { id: 'conv-signup', name: '注册成功', category: '注册', status: '已启用', count: 642 },
    { id: 'conv-game-start', name: '开始游戏', category: '自定义事件', status: '已启用', count: 1026 },
    { id: 'conv-form', name: '合作表单提交', category: '潜在客户', status: '未验证', count: 0 },
  ],
  ledger: [
    { id: 'txn-01', date: '2026-08-26 10:24', description: '演示充值', amount: 5000, type: '充值' },
    { id: 'txn-02', date: '2026-08-27 23:59', description: '推广计划日消耗', amount: -468.32, type: '消费' },
    { id: 'txn-03', date: '2026-08-28 12:00', description: '推广计划当日消耗', amount: -286.75, type: '消费' },
  ],
  preferences: {
    dateRange: '过去 30 天',
  },
};

export const WEEKLY_SERIES = [
  { day: '8/22', spend: 318, clicks: 672 },
  { day: '8/23', spend: 356, clicks: 744 },
  { day: '8/24', spend: 334, clicks: 712 },
  { day: '8/25', spend: 405, clicks: 856 },
  { day: '8/26', spend: 442, clicks: 932 },
  { day: '8/27', spend: 468, clicks: 978 },
  { day: '8/28', spend: 287, clicks: 624 },
];
